version: "3.9"

services: 
  mariadb:
    build: .
    container_name: mariadbtest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shop_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: 12345
      TZ: America/Mazatlan
    ports:
    - "3306:3306"
    volumes:
    - mariadb_data:/var/lib/mysql
    - ./init:/docker-entrypoint-initdb.d
    networks:
    - shop_net
volumes:
  mariadb_data:

networks:
  shop_net:
    driver: bridge